version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '1m'
    max-file: '1'
  driver: json-file

services:
  app:
    container_name: minesweeper
    volumes:
      - ./app:/app/
      - npm_cache:/root/.npm
      - node_modules:/app/node_modules
    ports:
      - 8080:3000
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    # env_file:
    #   - ./app/.env
    logging: *default-logging

volumes:
  npm_cache:
    driver: local
  node_modules:
    driver: local
